set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {clk}]

set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sel]
set_property PACKAGE_PIN C12 [get_ports rst]
set_property PACKAGE_PIN R17 [get_ports sel]

set_property IOSTANDARD LVCMOS33 [get_ports {seed[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seed[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {state[0]}]
set_property PACKAGE_PIN J15 [get_ports {seed[3]}]
set_property PACKAGE_PIN L16 [get_ports {seed[2]}]
set_property PACKAGE_PIN M13 [get_ports {seed[1]}]
set_property PACKAGE_PIN R15 [get_ports {seed[0]}]
set_property PACKAGE_PIN H17 [get_ports {state[3]}]
set_property PACKAGE_PIN K15 [get_ports {state[2]}]
set_property PACKAGE_PIN J13 [get_ports {state[1]}]
set_property PACKAGE_PIN N14 [get_ports {state[0]}]
