set_property IOSTANDARD LVCMOS33 [get_ports {count[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports direction]
set_property IOSTANDARD LVCMOS33 [get_ports mode_led]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN D9 [get_ports reset]
set_property PACKAGE_PIN A8 [get_ports direction]
set_property PACKAGE_PIN E1 [get_ports mode_led]
set_property PACKAGE_PIN T10 [get_ports {count[3]}]
set_property PACKAGE_PIN T9 [get_ports {count[2]}]
set_property PACKAGE_PIN J5 [get_ports {count[1]}]
set_property PACKAGE_PIN H5 [get_ports {count[0]}]
create_clock -period 10.000 -name clk [get_ports clk]
create_clock -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
